### PR TITLE
Add info on what storage to use with sparse mode

### PR DESCRIPTION
**Pull request by okdistribute**
I ran into this and couldn't figure it out for a bit, would be nice to have it on the readme.

### CODE REVIEW

**Comment by mafintosh** [comment]
Which issue did you run into with the normal raf and sparse mode?

**Comment by okdistribute** [comment]
It allocates the disk space for the whole dat even if it's only backing up one file.

**Comment by mafintosh** [comment]
The file it allocates is a sparse file so it takes up the same amount of space and has the benefit of only using a single fd.

**Comment by mafintosh** [comment]
Use `ls -alsh` to view the actual size (first column)

**Comment by okdistribute** [comment]
Okay interesting because my computer quickly runs out of space with random access files but seems to work fine with page files

**Comment by joehand** [comment]
The [sparse file ](https://en.wikipedia.org/wiki/Sparse_file) trick doesn't work on mac's fs (though that doesn't explain why page files wouldn't have same issue). But it should be 👌  on linux.

**Comment by mafintosh** [comment]
Ah yes. Linux/Windows only until the next macOS version that ships with APFS

**Comment by okdistribute** [comment]
Okay added a caveat for mac osx

**Pull request merged**
